### ISSUE TITLE
Can't concat bool to bytearray

### ISSUE THREAD

**Issue by rgruyters** [jlusiardi/homekit_python#119]
With Home Assistant I had added a Xiaomi Bedside Lamp 2 through Homekit Controller. When I want to control the light I get the following errors:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 148, in handle_call_service
    connection.context(msg))
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1133, in async_call
    self._execute_service(handler, service_call))
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1155, in _execute_service
    await handler.func(service_call)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_component.py", line 188, in handle_service
    self._platforms.values(), func, call, service_name
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/service.py", line 278, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/service.py", line 292, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/homekit_controller/light.py", line 137, in turn_off
    self.put_characteristics(characteristics)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/homekit_controller/__init__.py", line 310, in put_characteristics
    self._accessory.pairing.put_characteristics(chars)
  File "/usr/local/lib/python3.7/site-packages/homekit/controller.py", line 439, in put_characteristics
    response = self.session.put('/characteristics', data)
  File "/usr/local/lib/python3.7/site-packages/homekit/controller.py", line 647, in put
    return self.sec_http.put(url, body, content_type)
  File "/usr/local/lib/python3.7/site-packages/homekit/http_impl/secure_http.py", line 72, in put
    return self._handle_request(data)
  File "/usr/local/lib/python3.7/site-packages/homekit/http_impl/secure_http.py", line 92, in _handle_request
    return self._read_response()
  File "/usr/local/lib/python3.7/site-packages/homekit/http_impl/secure_http.py", line 159, in _read_response
    response.parse(decrypted)
  File "/usr/local/lib/python3.7/site-packages/homekit/http_impl/response.py", line 38, in parse
    self._raw_response += part
TypeError: can't concat bool to bytearray
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 220, in async_update_ha_state
    await self.async_device_update()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 348, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/homekit_controller/__init__.py", line 262, in update
    new_values_dict = pairing.get_characteristics(self._chars_to_poll)
  File "/usr/local/lib/python3.7/site-packages/homekit/controller.py", line 375, in get_characteristics
    response = self.session.get(url)
  File "/usr/local/lib/python3.7/site-packages/homekit/controller.py", line 637, in get
    return self.sec_http.get(url)
  File "/usr/local/lib/python3.7/site-packages/homekit/http_impl/secure_http.py", line 66, in get
    return self._handle_request(data)
  File "/usr/local/lib/python3.7/site-packages/homekit/http_impl/secure_http.py", line 92, in _handle_request
    return self._read_response()
  File "/usr/local/lib/python3.7/site-packages/homekit/http_impl/secure_http.py", line 159, in _read_response
    response.parse(decrypted)
  File "/usr/local/lib/python3.7/site-packages/homekit/http_impl/response.py", line 38, in parse
    self._raw_response += part
TypeError: can't concat bool to bytearray
```
I have already posted an issue on the Home Assistant Github page, https://github.com/home-assistant/home-assistant/issues/21793.
As far as I can read Traceback calls it looks like an issue with the Homekit Python module.

**Comment by jlusiardi** [comment]
Hey,

i should release a version 0.12.3, we have fixed that issue a while ago (see #89).

**Comment by jlusiardi** [comment]
@rgruyters can you try to increase the version for homekit to 0.12.3 and test again?

**Comment by rgruyters** [comment]
I have just tested it and works like a charm. Thanks for the fix.
What is the process for getting this into the next release of Home Assistant?

**Comment by rgruyters** [comment]
Maybe too soon. Still got an error. Doing a last check to make sure. Will let you know when I have tested again.

**Comment by rgruyters** [comment]
When I restarted Home Assistant it works fine for a few minutes. After that when I try to control the light I get the following message:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 220, in async_update_ha_state
    await self.async_device_update()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 348, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/homekit_controller/__init__.py", line 262, in update
    new_values_dict = pairing.get_characteristics(self._chars_to_poll)
  File "/config/deps/lib/python3.7/site-packages/homekit/controller.py", line 375, in get_characteristics
    response = self.session.get(url)
  File "/config/deps/lib/python3.7/site-packages/homekit/controller.py", line 637, in get
    return self.sec_http.get(url)
  File "/config/deps/lib/python3.7/site-packages/homekit/http_impl/secure_http.py", line 66, in get
    return self._handle_request(data)
  File "/config/deps/lib/python3.7/site-packages/homekit/http_impl/secure_http.py", line 92, in _handle_request
    return self._read_response()
  File "/config/deps/lib/python3.7/site-packages/homekit/http_impl/secure_http.py", line 159, in _read_response
    response.parse(decrypted)
  File "/config/deps/lib/python3.7/site-packages/homekit/http_impl/response.py", line 38, in parse
    self._raw_response += part
TypeError: can't concat bool to bytearray
```

**Comment by jlusiardi** [comment]
hey,

I am confused. Are you sure, that HomeAssistent uses Version 0.12.3?

just took a look into a downloaded version of `homekit==0.12.3`, but the block around secure_http.py line 136 looks like:
```
131             if decrypted is not False:
132                 response.parse(decrypted)
133             else:
134                 try:
135                     self.sock.close()
136                 except OSError:
137                     pass
138                 raise exceptions.EncryptionError('Error during transmission.')
139 
140             # check how long next block will be
141             if int.from_bytes(tmp[0:2], 'little') < 1024:
```
The `TypeError: can't concat bool to bytearray` look familiar, but the `ValueError: negative buffersize in recv` is new though.

**Comment by rgruyters** [comment]
I have checked and looks the same.

Here is the lines from my environment.
```
            decrypted = self.decrypt_block(length, block, tag)
            if decrypted is not False:
                response.parse(decrypted)
            else:
                try:
                    self.sock.close()
                except OSError:
                    pass
                raise exceptions.EncryptionError('Error during transmission.')

            # check how long next block will be
            if int.from_bytes(tmp[0:2], 'little') < 1024:
                exp_len = int.from_bytes(tmp[0:2], 'little') - len(tmp) + 18
```

**Comment by rgruyters** [comment]
Found the issue. (I think)
With Hass.io there is another (second) location of Python libraries. (/config/deps/lib/python3.7)
Why beats me, but I will try to update this as well to see if it will fix my problem.

**Comment by rgruyters** [comment]
It works fine now. Apparently I have installed local Python module in my `/config/deps` folder. Which overrule the default `/usr/local/lib/python`. 

Sorry for all the problems, but the problem is solved.

**Comment by jlusiardi** [comment]
Hey @rgruyters,
no problem. I am always learning new stuff and I am glad to help.

**Comment by evisser4** [comment]
How do I force home assistant to require 0.12.3?

**Comment by jlusiardi** [comment]
Hi @evisser4,

since this is not an issue with `homekit_python` I can't really help you. Perhaps you should ask the folks from homeassistant in their project?

Joachim

**Comment by rgruyters** [comment]
> How do I force home assistant to require 0.12.3?

You have to copy the component from `homassistant/components/homekit_controller` folder and copy it to `custom_components` folder. Update the `REQUIREMENT` statement in `__init__.py`, and restart your environment.
