### ISSUE TITLE
Adapter "hci0" does not suit our needs

### ISSUE THREAD

**Issue by voynovia** [jlusiardi/homekit_python#138]
**python3 -m homekit.discover_ble --log DEBUG**

`Adapter "hci0" does not suit our needs
2019-05-09 21:56:30,184 discover_ble.py:0045 DEBUG Adapter "hci0" does not suit our needs
Traceback (most recent call last):
  File "/home/pi/python/homekit_python/homekit/discover_ble.py", line 42, in <module>
    devices = Controller.discover_ble(args.timeout, args.adapter)
  File "/home/pi/python/homekit_python/homekit/controller/controller.py", line 114, in discover_ble
    manager = DiscoveryDeviceManager(adapter)
  File "/home/pi/python/homekit_python/homekit/controller/ble_impl/gatt.py", line 125, in __init__
    raise BluetoothAdapterError('Adapter "{a}" does not suit our needs'.format(a=adapter_name))
homekit.exceptions.BluetoothAdapterError: Adapter "hci0" does not suit our needs`

Why?

**Comment by jlusiardi** [comment]
Hello,

ok, the error message is not expressing the real issue. It seems that it does not have Bluetooth LE in a supported fashion? What kind of adapter is it?

I will change the error message to be more clear.

Regards
Joachim

**Comment by voynovia** [comment]
> ok, the error message is not expressing the real issue. It seems that it does not have Bluetooth LE in a supported fashion? 

'hcitool lescan' works

>What kind of adapter is it?

This is Raspberry Pi 3 B+

**Comment by jlusiardi** [comment]
Interesting, I will have to investigate

**Comment by jlusiardi** [comment]
@voynovia can you change line 26 of `` from 
```
return 'org.bluez.LEAdvertisingManager1' in ifaces
```
to
```
print(ifaces)
return True
``` 
and attach the result?

**Comment by jlusiardi** [comment]
I tried to improve the situation in branch `fix_138_adapter_not_suitable`. Can you use this branch to test if you think it improves your situation?

**Comment by voynovia** [comment]
Adapter "hci0" seems not to support Bluetooth LE, the command might not function properly!
Bluetooth adapter not ready. Set `is_adapter_powered` to `True` or run 'echo "power on" | sudo bluetoothctl'.
2019-05-11 19:53:05,399 discover_ble.py:0045 DEBUG Bluetooth adapter not ready. Set `is_adapter_powered` to `True` or run 'echo "power on" | sudo bluetoothctl'.
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/gatt/gatt_linux.py", line 138, in start_discovery
    self._adapter.SetDiscoveryFilter(discovery_filter)
  File "/home/pi/.local/lib/python3.5/site-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/home/pi/.local/lib/python3.5/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/home/pi/.local/lib/python3.5/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)

dbus.exceptions.DBusException: org.bluez.Error.NotReady: Resource Not Ready

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/pi/python/homekit_python/homekit/discover_ble.py", line 42, in <module>
    devices = Controller.discover_ble(args.timeout, args.adapter)
  File "/home/pi/python/homekit_python/homekit/controller/controller.py", line 115, in discover_ble
    manager.start_discovery()
  File "/home/pi/python/homekit_python/homekit/controller/ble_impl/discovery.py", line 50, in start_discovery
    return super().start_discovery()
  File "/home/pi/.local/lib/python3.5/site-packages/gatt/gatt_linux.py", line 143, in start_discovery
    "Bluetooth adapter not ready. "
gatt.errors.NotReady: Bluetooth adapter not ready. Set `is_adapter_powered` to `True` or run 'echo "power on" | sudo bluetoothctl'.

**Comment by jlusiardi** [comment]
Hi,

ok, this looks like the adapter is not powered on.

Can you execute  `echo "power on" | sudo bluetoothctl` and see if it works?

**Comment by jlusiardi** [comment]
ok, now the adapter should be turned on before usage, can you give it another try?

**Comment by jlusiardi** [comment]
should work after merging #141 so I will close this now
