### ISSUE TITLE
JSON Decode Error

### ISSUE THREAD

**Issue by jakeapp** [jlusiardi/homekit_python#143]
Working on getting a currently unsupported thermostat paired and working (Shout out to Jc2k and jlusuardi on all the upgrades!)

```
2019-06-10 16:25:20,890 ip_implementation.py:0418 DEBUG session established
Expecting value: line 1 column 1 (char 0)
2019-06-10 16:25:30,904 pair.py:0085 DEBUG Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homekit/pair.py", line 80, in <module>
    pairing.list_accessories_and_characteristics()
  File "/srv/homeassistant/lib/python3.6/site-packages/homekit/controller/ip_implementation.py", line 81, in list_accessories_and_characteristics
    accessories = json.loads(tmp)['accessories']
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Line 33 in:  /homekit/model/feature_flags.py  throws:

```
[KeyError: 'Item 2 not found’]
```
during discovery

without line 33 discovery shows:

```
Name: iComfort S30 xxxxxx._hap._tcp.local.
Url: http_impl://192.168.x.xx:7373
Configuration number (c#): 1
Feature Flags (ff): Supports HAP Pairing (Flag: 1)
Device ID (id): xx:xx:xx:xx:xx:xx
Model Name (md): S30 2B
Protocol Version (pv): 1.0
State Number (s#): 1
Status Flags (sf): Accessory has been paired. (Flag: 0)
Category Identifier (ci): Thermostat (Id: 9)
```

if done through hass this error also happens:

```
  File "/srv/homeassistant/lib/python3.6/site-packages/homekit/controller/controller.py", line 370, in start_pairing
    raise AlreadyPairedError('Alias "{a}" is already paired.'.format(a=alias))
homekit.exceptions.AlreadyPairedError: Alias “xx:xx:xx:xx:xx:xx” is already paired.
```
The thermostat indicates on the display a successful pairing even though homekit_python isn't quite getting it...  Reseting the "homekit user" on the thermostat; changes the status flags back to unpaired in discovery...

If the pair command is run again without resetting the homekit user on the thermostat:

```
2019-06-10 16:46:17,810 __init__.py:0118 DEBUG #3 ios -> accessory: send SRP verify request
step 3
2019-06-10 16:46:17,811 pair.py:0085 DEBUG step 3
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homekit/pair.py", line 77, in <module>
    finish_pairing = controller.start_pairing(args.alias, args.device)
  File "/srv/homeassistant/lib/python3.6/site-packages/homekit/controller/controller.py", line 379, in start_pairing
    salt, pub_key = perform_pair_setup_part1(write_fun)
  File "/srv/homeassistant/lib/python3.6/site-packages/homekit/protocol/__init__.py", line 127, in perform_pair_setup_part1
    error_handler(response_tlv[1][1], 'step 3')
  File "/srv/homeassistant/lib/python3.6/site-packages/homekit/protocol/__init__.py", line 43, in error_handler
    raise UnavailableError(stage)
homekit.exceptions.UnavailableError: step 3
```

**Comment by jlusiardi** [comment]
Hello @jakeapp,

thanks for your bug report. 

The pairing seems to work, at least the device thinks it is paired. The code from this project assumes that there is only bit 1 used in the feature flags (as specified in the HomeKit Accessory Protocol Specification page 69, table 5-8). Apparently Apple extended this and uses bit 2 now for some information. I will push a fix later today into a branch. 

The error you got when trying to repair your device without removing the HomeKit user is intended since you cannot add a second user this way. There are other ways (I think, not implemented in this project). 

Regards
Joachim
