### ISSUE TITLE
Unable to unpair Lifx Tiles

### ISSUE THREAD

**Issue by netmanchris** [jlusiardi/homekit_python#146]
Testing out the LIFX Tiles product and I'm unable to remove the homekit pairing. 

Let me know if more information is required. Happy to get whatever we need.

* device manufacturer : **LIFX**
 * device model : **LIFX Tiles**
 * device firmware version : **3.50**
 * device hardware version : **1.0**
 * communication channel : **IP**
 * version of *homekit* library: **0.14.0**
Symptom: Python exception

Command
**python -m homekit.unpair -f lifx -a tiles --log debug**
Debug
```
2019-07-05 17:57:06,559 tlv.py:0134 DEBUG sending [
  6: (1 bytes) 0x01
  0: (1 bytes) 0x04
  1: (36 bytes) b'0f7546ff-351c-453c-92f6-936cc271778e'
]

2019-07-05 17:57:06,559 ip_implementation.py:0391 DEBUG init session
2019-07-05 17:57:06,629 tlv.py:0134 DEBUG sending [
  6: (1 bytes) 0x01
  3: (32 bytes) b'7to2\xce-p0\xd9\x07Z#\xacuE\x14\x15\xad\x16"\xc7\x1bt\xd8\x94u\xbe\xe1\x87\xc7]k'
]

2019-07-05 17:57:06,629 tlv.py:0117 DEBUG receiving [
  6: (1 bytes) 0x01
  3: (32 bytes) 0x37746f32ce2d7030d9075a23ac75451415ad1622c71b74d89475bee187c75d6b
]

2019-07-05 17:57:06,629 __init__.py:0075 DEBUG write message: [
  6: (1 bytes) 0x01
  3: (32 bytes) 0x37746f32ce2d7030d9075a23ac75451415ad1622c71b74d89475bee187c75d6b
]

2019-07-05 17:57:06,730 tlv.py:0117 DEBUG receiving [
  6: (1 bytes) 0x02
  3: (32 bytes) 0xafe0f0016c567c076328447c2d41633fedf8ea0b7b5575e103358943d624d745
  5: (101 bytes) 0xa7e6d448fa37130352a724bf4db9ba3e4fb45882e17e69b7212a57c33cd2c41017b7557e6027a2697614ecee7ac9687bdaad5dba539b762bfbd7b3732f92829a835d16d2545c9610ec6e0eabf49928cebd89356135ed159db8e958b758b139ec58dd87ff65
]

2019-07-05 17:57:06,731 __init__.py:0082 DEBUG response: [
  6: (1 bytes) 0x02
  3: (32 bytes) 0xafe0f0016c567c076328447c2d41633fedf8ea0b7b5575e103358943d624d745
  5: (101 bytes) 0xa7e6d448fa37130352a724bf4db9ba3e4fb45882e17e69b7212a57c33cd2c41017b7557e6027a2697614ecee7ac9687bdaad5dba539b762bfbd7b3732f92829a835d16d2545c9610ec6e0eabf49928cebd89356135ed159db8e958b758b139ec58dd87ff65
]

2019-07-05 17:57:06,734 tlv.py:0117 DEBUG receiving [
  1: (17 bytes) 0x43383a33413a41353a46443a44413a3130
  10: (64 bytes) 0x7247a6f621e02f8eb9b35f9b2e692bbfdba3eb520390cedabcb1ee19adc20205e1b5908c70d3b63aff219814a48f622728f4c79fb051bb9e12e03c287858780d
]

2019-07-05 17:57:06,737 tlv.py:0134 DEBUG sending [
  1: (36 bytes) b'0f7546ff-351c-453c-92f6-936cc271778e'
  10: (64 bytes) b'\xba\x9f*Cs\x98\xc4A\xc7u\xbdT\xd9S\xcd\xc9\xbf0\xbbGqG\xfa\xb2\x11e\x983\x92IC"W\x90\xab1?S\x97"t#\xaa4r~\xfb\xbfm\x05\x81\xe1{\x1da\t\xc9os\xc5XA\xed\x03'
]

2019-07-05 17:57:06,739 tlv.py:0134 DEBUG sending [
  6: (1 bytes) 0x03
  5: (120 bytes) 0x62df0b1d3885e0c61966f88b172af29ef38e631e67a8522a09cfa9ffaea550c79b400df61801989949742989a7511614b8afcf88e39e87652a267c67b90f6dd0c6c856ce30a4888df9ff117a6eee001aadda9af425848bf1c328f6624aca9f28f60af6dbacf7789968fbb48ccd066e150af51485acd43d80
]

2019-07-05 17:57:06,739 tlv.py:0117 DEBUG receiving [
  6: (1 bytes) 0x03
  5: (120 bytes) 0x62df0b1d3885e0c61966f88b172af29ef38e631e67a8522a09cfa9ffaea550c79b400df61801989949742989a7511614b8afcf88e39e87652a267c67b90f6dd0c6c856ce30a4888df9ff117a6eee001aadda9af425848bf1c328f6624aca9f28f60af6dbacf7789968fbb48ccd066e150af51485acd43d80
]

2019-07-05 17:57:06,740 __init__.py:0075 DEBUG write message: [
  6: (1 bytes) 0x03
  5: (120 bytes) 0x62df0b1d3885e0c61966f88b172af29ef38e631e67a8522a09cfa9ffaea550c79b400df61801989949742989a7511614b8afcf88e39e87652a267c67b90f6dd0c6c856ce30a4888df9ff117a6eee001aadda9af425848bf1c328f6624aca9f28f60af6dbacf7789968fbb48ccd066e150af51485acd43d80
]

2019-07-05 17:57:06,804 tlv.py:0117 DEBUG receiving [
  6: (1 bytes) 0x04
]

2019-07-05 17:57:06,805 __init__.py:0082 DEBUG response: [
  6: (1 bytes) 0x04
]

2019-07-05 17:57:06,805 ip_implementation.py:0418 DEBUG session established
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/christopheryoung/PycharmProjects/netmanchris_homekit/venv/lib/python3.7/site-packages/homekit-0.13.0-py3.7.egg/homekit/unpair.py", line 46, in <module>
  File "/Users/christopheryoung/PycharmProjects/netmanchris_homekit/venv/lib/python3.7/site-packages/homekit-0.13.0-py3.7.egg/homekit/controller/controller.py", line 500, in remove_pairing
  File "/Users/christopheryoung/PycharmProjects/netmanchris_homekit/venv/lib/python3.7/site-packages/homekit-0.13.0-py3.7.egg/homekit/protocol/tlv.py", line 96, in decode_bytes
  File "/Users/christopheryoung/PycharmProjects/netmanchris_homekit/venv/lib/python3.7/site-packages/homekit-0.13.0-py3.7.egg/homekit/protocol/tlv.py", line 110, in decode_bytearray
homekit.protocol.tlv.TlvParseException: Not enough data for length 34
```

**Comment by jlusiardi** [comment]
hey, seems like the version is 0.13.0 and not 0.14.0(`site-packages/homekit-0.13.0-py3.7.egg/`). can you retry with 0.14.0? Not sure this will fix anything but just not to chase old issues.

**Comment by jlusiardi** [comment]
I think we can close this because of inactivity.
