### ISSUE TITLE
IP Discovery is not working on MacOs

### ISSUE THREAD

**Issue by niemyjski** [jlusiardi/homekit_python#158]
I ran the following command  (latest stable of everything)

```
python3 -m homekit.discover --log DEBUG
....
2019-08-18 09:48:58,415 __init__.py:0099 DEBUG candidate data {b'c#': b'1', b'ff': b'8', b'id': b'XX:XX:XX:XX:XX:XX', b'md': b'WEBOS', b'pv': b'1.1', b's#': b'1', b'sf': b'1', b'ci': b'31', b'sh': b'3mxJYw=='}

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/blake/Library/Python/3.7/lib/python/site-packages/homekit/discover.py", line 51, in <module>
    results = Controller.discover(args.timeout)
  File "/Users/blake/Library/Python/3.7/lib/python/site-packages/homekit/controller/controller.py", line 90, in discover
    return discover_homekit_devices(max_seconds)
  File "/Users/blake/Library/Python/3.7/lib/python/site-packages/homekit/zeroconf_impl/__init__.py", line 102, in discover_homekit_devices
    info.properties
  File "/Users/blake/Library/Python/3.7/lib/python/site-packages/homekit/zeroconf_impl/__init__.py", line 180, in parse_discovery_properties
    d['category'] = Categories[int(category)]
  File "/Users/blake/Library/Python/3.7/lib/python/site-packages/homekit/model/categories.py", line 94, in __getitem__
    raise KeyError('Item {item} not found'.format(item=item))
KeyError: 'Item 31 not found'
```

I'm guessing it has to do with not supporting my LG c9 tv (wonder what it will do when I get the homekit component for my shower :D). https://www.theverge.com/2019/7/24/20708380/lg-apple-airplay-2-homekit-2019-oled-microcell-uhd-tv

**Comment by jlusiardi** [comment]
looks like #131 and #136 is still open. 
The listing of IDs from Table 12-3 Accessory Categories are limited. There are new categories in new devices but I do not know them. Should make a generic solution and map unknown categories to "Category 31' in this case?

**Comment by jlusiardi** [comment]
@niemyjski can you try to use https://github.com/jlusiardi/homekit_python/tree/fix_158_unknown_categories in HASS.io or directly to do `python3 -m homekit.discover --log DEBUG`?

**Comment by niemyjski** [comment]
Yes, is there an easy way to update to this branch using pip3?
Thanks
-Blake Niemyjski

**Comment by jlusiardi** [comment]
Hi,
should be doable with `pip3 install --user -e git+https://github.com/jlusiardi/homekit_python.git@fix_158_unknown_categories#egg=homekit`
-Joachim

**Comment by niemyjski** [comment]
Sweet! That worked

```
Name: LG webOS TV D6DC._hap._tcp.local.
Url: http_impl://10.0.72.47:44456
Configuration number (c#): 1
Feature Flags (ff): No support for HAP Pairing (Flag: 8)
Device ID (id): XX:XX:XX:XX:XX:XX
Model Name (md): WEBOS
Protocol Version (pv): 1.1
State Number (s#): 1
Status Flags (sf): Accessory has not been paired with any controllers. (Flag: 1)
Category Identifier (ci): Unknown Category #31 (Id: 31)
```

**Comment by jlusiardi** [comment]
Hey @niemyjski ,
cool! Can you also pair it and use the other homekit tools?
Joachim

**Comment by Jc2k** [comment]
@jlusiardi in case of delays with timezones i figured i should post the original exception from the [Home Assistant side of things](https://github.com/home-assistant/home-assistant/issues/25960). When trying to verify the pairing code with the TV we are seeing:

```
2019-08-15 05:07:07 ERROR (MainThread) [homeassistant.components.homekit_controller.config_flow] Pairing attempt failed with an unhandled exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/homekit_controller/config_flow.py", line 250, in async_step_pair
    await self.hass.async_add_executor_job(self.finish_pairing, code)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/homekit/controller/controller.py", line 391, in finish_pairing
    pairing = perform_pair_setup_part2(pin, str(uuid.uuid4()), write_fun, salt, pub_key)
  File "/usr/local/lib/python3.7/site-packages/homekit/protocol/__init__.py", line 173, in perform_pair_setup_part2
    assert response_tlv[0][0] == TLV.kTLVType_State and response_tlv[0][1] == TLV.M4, \
IndexError: list index out of range
```

@niemyjski is running 0.97.2 here, so the homekit_python version will be 0.15.0.

**Comment by niemyjski** [comment]
I'll try pairing it today or tomorrow. I didn't know what I needed to specify for the `-f` flag. @Jc2k responded to that question last night. Seems like that should be optional as a file could be created with the device name in a sub directory of the install folder.

**Comment by Jc2k** [comment]
To me, this looks like a completely normal M1/M2/M3 exchange, then the TV abruptly returns nothing / closes the connection instead of sending us an M4. There are no extra fields or new reserved flags suddenly being used in the M2 to indicate we should behave differently. I wondered if they rolled out a new pairing scheme (different salt? pub key?) There is no new spec, though. That likely means it failed the SRP proof? But that kind of error should (according to the spec) yield an M4 response with a `kTLVType_Error`.

**Comment by jlusiardi** [comment]
@niemyjski and  @jc2k: i would like to close this and move the issue to #170, since this is not discovery related anymore and we seem to have the same issue with at least the Eve Energy 1EC0 plug as well.

**Comment by Jc2k** [comment]
Fine by me!

**Comment by jlusiardi** [comment]
Continued in #170!
