### ISSUE TITLE
Broken Pipe

### ISSUE THREAD

**Issue by sberryman** [jlusiardi/homekit_python#22]
I'm using Home Assistant and seeing a lot of broken pipe errors, any idea what would be causing these? Is it related to issue #21 and using MAC address vs IP address? My switch has a static IP address.

```shell
2018-05-03 13:18:14 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.isp5 fails
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 204, in async_update_ha_state
    yield from self.async_device_update()
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 327, in async_device_update
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/homekit_controller/__init__.py", line 196, in update
    response = self._securecon.get('/accessories')
  File "/srv/homeassistant/lib/python3.5/site-packages/homekit/secure_http.py", line 63, in get
    return self._handle_request(data)
  File "/srv/homeassistant/lib/python3.5/site-packages/homekit/secure_http.py", line 86, in _handle_request
    self.sock.send(len_bytes + ciper_and_mac[0] + ciper_and_mac[1])
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by jlusiardi** [comment]
can you please describe the setup in more details? With switch you refer to the HomeKit Accessory? Is the Wifi Connection stable to the device? Looks like the connection is unstable and therefore the pipe breaks. 

How often does this happen? Do you have more than one accessory?

**Comment by jlusiardi** [comment]
Closing because of the missing feedback.
