### ISSUE TITLE
from homekit import AccessoryServer

### ISSUE THREAD

**Issue by andreyxc** [jlusiardi/homekit_python#241]
File "c:\Users\korya\homekit_test\test.py", line 6, in <module>
    from homekit import AccessoryServer
  File "c:\Users\korya\homekit_test\homekit\__init__.py", line 26, in <module>
    from homekit.controller import Controller
  File "c:\Users\korya\homekit_test\homekit\controller\__init__.py", line 21, in <module>
    from homekit.controller.controller import Controller, PairingAuth, PairingAuthMap
  File "c:\Users\korya\homekit_test\homekit\controller\controller.py", line 30, in <module>
    from homekit.protocol import States, Methods, Errors, TlvTypes
  File "c:\Users\korya\OneDrive\homekit_test\homekit\protocol\__init__.py", line 18, in <module>
    import ed25519
ModuleNotFoundError: No module named 'ed25519'

**Comment by andreyxc** [comment]
What could be ?

**Comment by andreyxc** [comment]
python3 demoserver.py

2022-09-04 19:37:28,763 demoserver.py:0048 INFO starting
Traceback (most recent call last):
File "/home/pi/homekit_python-master/demoserver.py", line 62, in
httpd.publish_device()
File "/home/pi/homekit_python-master/homekit/accessoryserver.py", line 1347, in publish_device
self.zeroconf.check_service(self.zeroconf_info, allow_name_change=False)
AttributeError: 'Zeroconf' object has no attribute 'check_service'

**Comment by andreyxc** [comment]
Traceback (most recent call last):
  File "/home/pi/homekit_python-master/demoserver.py", line 37, in <module>
    httpd.publish_device()
  File "/home/pi/homekit_python-master/homekit/accessoryserver.py", line 1347, in publish_device
    self.zeroconf.check_service(self.zeroconf_info, allow_name_change=False)
AttributeError: 'Zeroconf' object has no attribute 'check_service'

**Comment by andreyxc** [comment]
zeroconf==0.32.0 !
