### ISSUE TITLE
Pairing fails with Hue bridge

### ISSUE THREAD

**Issue by mjg59** [jlusiardi/homekit_python#35]
Trying to pair with a Hue bridge:

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/hap/lib/python3.5/site-packages/homekit/pair.py", line 55, in <module>
    pairing = perform_pair_setup(conn, args.pin, iOSPairingId)
  File "/tmp/hap/lib/python3.5/site-packages/homekit/protocol.py", line 102, in perform_pair_setup
    assert response_tlv[TLV.kTLVType_State] == TLV.M4
AssertionError

The response is {6: bytearray(b'\x02'), 7: bytearray(b'\x01')}, so I assume that it's unhappy about something happening during step 3.

**Comment by mjg59** [comment]
Ok the Hue is sensitive to the order of the TLVs at this point - if kTLVType_State isn't first, it returns an error.

**Comment by mjg59** [comment]
Fixed by #36
