### ISSUE TITLE
homekit.discover: UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f4a6' in position 6: character maps to <undefined>

### ISSUE THREAD

**Issue by lboue** [jlusiardi/homekit_python#40]
Hello,

I installed homekit_python on my raspberrypi and run homekit.discover. I am running Python 3.5.3. 
I am getting many "UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f4a6' in position 6: character maps to <undefined>" error.

What can I do to fix that?

Debug log
```
pi@raspberrypi:~ $  python3 -m homekit.discover
Name: Temperature Sensor-1B6A._hap._tcp.local.
Url: http://192.168.1.91:52834
Configuration number (c#): 2
Feature Flags (ff): Paired (Flag: 0)
Device ID (id): C1:5D:3A:AE:5E:FA
Model Name (md): Temperature Sensor
Protocol Version (pv): 1.0
State Number (s#): 1
Status Flags (sf): 1
Category Identifier (ci): Other (Id: 1)

Name: Philips hue - 28DE56._hap._tcp.local.
Url: http://192.168.1.19:8080
Configuration number (c#): 12
Feature Flags (ff): Supports Pairing (Flag: 1)
Device ID (id): EA:9B:7A:A6:7F:31
Model Name (md): BSB002
Protocol Version (pv): 1.1
State Number (s#): 1
Status Flags (sf): 0
Category Identifier (ci): Bridge (Id: 2)

Name: Thermostat 1-19DA._hap._tcp.local.
Url: http://192.168.1.91:52835
Configuration number (c#): 2
Feature Flags (ff): Paired (Flag: 0)
Device ID (id): CA:3E:BC:4D:5E:FF
Model Name (md): Thermostat 1
Protocol Version (pv): 1.0
State Number (s#): 1
Status Flags (sf): 1
Category Identifier (ci): Other (Id: 1)

Name: Garage Door-E0CE._hap._tcp.local.
Url: http://192.168.1.91:52828
Configuration number (c#): 2
Feature Flags (ff): Paired (Flag: 0)
Device ID (id): C1:5D:3F:EE:5E:FA
Model Name (md): Garage Door
Protocol Version (pv): 1.0
State Number (s#): 1
Status Flags (sf): 1
Category Identifier (ci): Other (Id: 1)

Name: Outlet-FFC3._hap._tcp.local.
Url: http://192.168.1.91:52832
Configuration number (c#): 2
Feature Flags (ff): Paired (Flag: 0)
Device ID (id): 1A:2B:3C:4D:5D:FF
Model Name (md): Outlet
Protocol Version (pv): 1.0
State Number (s#): 1
Status Flags (sf): 1
Category Identifier (ci): Other (Id: 1)

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/.local/lib/python3.5/site-packages/homekit/discover.py", line 32, in <module>
    discover_homekit_devices()
  File "/home/pi/.local/lib/python3.5/site-packages/homekit/zeroconf_.py", line 47, in discover_homekit_devices
    print('Name: {name}'.format(name=info.name))
  File "/usr/lib/python3.5/encodings/iso8859_15.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f4a6' in position 6: character maps to <undefined>
```

**Comment by jlusiardi** [comment]
Hi,

could you try **avahi-discover** or something else to find out which name causes the trouble in line 47 in zeroconf_.py?

I will try to work on the issue in https://github.com/jlusiardi/homekit_python/tree/fix_40_UnicodeEncodeError_while_discov

Regards
Joachim

**Comment by lboue** [comment]
This is odd. If I start multiple times the same discover.py script. Each time, I am getting a different output but I can't reproduce the issue anymore. 

A PCAP trace here: https://drive.google.com/file/d/1HQhMo1J3lSaa89oknHfuReutDU6N904U/view?usp=sharing

### 1st time
```
pi@raspberrypi:~/homekit_python $ python3 homekit/discover.py 
Name: DemoAccessory._hap._tcp.local.
Url: http://192.168.1.91:8081
Configuration number (c#): 1
Feature Flags (ff): Paired (Flag: 0)
Device ID (id): 12:00:00:00:00:00
Model Name (md): My Lightbulb
Protocol Version (pv): 1.0
State Number (s#): 1
Status Flags (sf): 0
Category Identifier (ci): Lightbulb (Id: 5)

Name: Philips hue - 28DE56._hap._tcp.local.
Url: http://192.168.1.19:8080
Configuration number (c#): 12
Feature Flags (ff): Supports Pairing (Flag: 1)
Device ID (id): EA:9B:7A:A6:7F:31
Model Name (md): BSB002
Protocol Version (pv): 1.1
State Number (s#): 1
Status Flags (sf): 0
Category Identifier (ci): Bridge (Id: 2)

Name: Motion Sensor-2CCC._hap._tcp.local.
Url: http://192.168.1.91:52831
Configuration number (c#): 2
Feature Flags (ff): Paired (Flag: 0)
Device ID (id): 1A:2B:3D:4D:2E:AF
Model Name (md): Motion Sensor
Protocol Version (pv): 1.0
State Number (s#): 1
Status Flags (sf): 1
Category Identifier (ci): Other (Id: 1)

Name: Fan-E78C._hap._tcp.local.
Url: http://192.168.1.91:52827
Configuration number (c#): 7
Feature Flags (ff): Paired (Flag: 0)
Device ID (id): 1A:2B:3C:4D:5E:FF
Model Name (md): Fan
Protocol Version (pv): 1.0
State Number (s#): 1
Status Flags (sf): 1
Category Identifier (ci): Other (Id: 1)

Name: ðŸ’¦ Sprinkler-C551._hap._tcp.local.
Url: http://192.168.1.91:52833
Configuration number (c#): 2
Feature Flags (ff): Paired (Flag: 0)
Device ID (id): A3:AB:3D:4D:2E:A3
Model Name (md): ðŸ’¦ Sprinkler
Protocol Version (pv): 1.0
State Number (s#): 1
Status Flags (sf): 0
Category Identifier (ci): Other (Id: 1)

Name: Outlet-FFC3._hap._tcp.local.
Url: http://192.168.1.91:52832
Configuration number (c#): 2
Feature Flags (ff): Paired (Flag: 0)
Device ID (id): 1A:2B:3C:4D:5D:FF
Model Name (md): Outlet
Protocol Version (pv): 1.0
State Number (s#): 1
Status Flags (sf): 1
Category Identifier (ci): Other (Id: 1)

Name: Simple Light-83BF._hap._tcp.local.
Url: http://192.168.1.91:52829
Configuration number (c#): 2
Feature Flags (ff): Paired (Flag: 0)
Device ID (id): FA:3C:ED:5A:1A:1A
Model Name (md): Simple Light
Protocol Version (pv): 1.0
State Number (s#): 1
Status Flags (sf): 1
Category Identifier (ci): Other (Id: 1)

Name: Lock-0C82._hap._tcp.local.
Url: http://192.168.1.91:52830
Configuration number (c#): 2
Feature Flags (ff): Paired (Flag: 0)
Device ID (id): C1:5D:3A:EE:5E:FA
Model Name (md): Lock
Protocol Version (pv): 1.0
State Number (s#): 1
Status Flags (sf): 1
Category Identifier (ci): Other (Id: 1)

Name: Temperature Sensor-1B6A._hap._tcp.local.
Url: http://192.168.1.91:52834
Configuration number (c#): 2
Feature Flags (ff): Paired (Flag: 0)
Device ID (id): C1:5D:3A:AE:5E:FA
Model Name (md): Temperature Sensor
Protocol Version (pv): 1.0
State Number (s#): 1
Status Flags (sf): 1
Category Identifier (ci): Other (Id: 1)

Name: Air Conditioner-E78C._hap._tcp.local.
Url: http://192.168.1.91:52826
Configuration number (c#): 6
Feature Flags (ff): Paired (Flag: 0)
Device ID (id): 1A:2B:3C:4D:5E:FF
Model Name (md): Air Conditioner
Protocol Version (pv): 1.0
State Number (s#): 1
Status Flags (sf): 1
Category Identifier (ci): Other (Id: 1)

Name: Thermostat 1-19DA._hap._tcp.local.
Url: http://192.168.1.91:52835
Configuration number (c#): 2
Feature Flags (ff): Paired (Flag: 0)
Device ID (id): CA:3E:BC:4D:5E:FF
Model Name (md): Thermostat 1
Protocol Version (pv): 1.0
State Number (s#): 1
Status Flags (sf): 1
Category Identifier (ci): Other (Id: 1)

Name: Garage Door-E0CE._hap._tcp.local.
Url: http://192.168.1.91:52828
Configuration number (c#): 2
Feature Flags (ff): Paired (Flag: 0)
Device ID (id): C1:5D:3F:EE:5E:FA
Model Name (md): Garage Door
Protocol Version (pv): 1.0
State Number (s#): 1
Status Flags (sf): 1
Category Identifier (ci): Other (Id: 1)
```

### 2nd time
```
pi@raspberrypi:~/homekit_python $ python3 homekit/discover.py 
Name: DemoAccessory._hap._tcp.local.
Url: http://192.168.1.91:8081
Configuration number (c#): 1
Feature Flags (ff): Paired (Flag: 0)
Device ID (id): 12:00:00:00:00:00
Model Name (md): My Lightbulb
Protocol Version (pv): 1.0
State Number (s#): 1
Status Flags (sf): 0
Category Identifier (ci): Lightbulb (Id: 5)

Name: Homebridge-E493._hap._tcp.local.
Url: http://192.168.1.91:51826
Configuration number (c#): 38296
Feature Flags (ff): Paired (Flag: 0)
Device ID (id): CC:21:3E:E4:DE:33
Model Name (md): Homebridge
Protocol Version (pv): 1.0
State Number (s#): 1
Status Flags (sf): 0
Category Identifier (ci): Bridge (Id: 2)

Name: Philips hue - 28DE56._hap._tcp.local.
Url: http://192.168.1.19:8080
Configuration number (c#): 12
Feature Flags (ff): Supports Pairing (Flag: 1)
Device ID (id): EA:9B:7A:A6:7F:31
Model Name (md): BSB002
Protocol Version (pv): 1.1
State Number (s#): 1
Status Flags (sf): 0
Category Identifier (ci): Bridge (Id: 2)
```

### 3rd time
```
pi@raspberrypi:~/homekit_python $ python3 homekit/discover.py 
Name: DemoAccessory._hap._tcp.local.
Url: http://192.168.1.91:8081
Configuration number (c#): 1
Feature Flags (ff): Paired (Flag: 0)
Device ID (id): 12:00:00:00:00:00
Model Name (md): My Lightbulb
Protocol Version (pv): 1.0
State Number (s#): 1
Status Flags (sf): 0
Category Identifier (ci): Lightbulb (Id: 5)

Name: Philips hue - 28DE56._hap._tcp.local.
Url: http://192.168.1.19:8080
Configuration number (c#): 12
Feature Flags (ff): Supports Pairing (Flag: 1)
Device ID (id): EA:9B:7A:A6:7F:31
Model Name (md): BSB002
Protocol Version (pv): 1.1
State Number (s#): 1
Status Flags (sf): 0
Category Identifier (ci): Bridge (Id: 2)

Name: Camera Name-FEAB._hap._tcp.local.
Url: http://192.168.1.91:44337
Configuration number (c#): 2
Feature Flags (ff): Paired (Flag: 0)
Device ID (id): EA:C7:55:4B:9B:80
Model Name (md): Camera Name
Protocol Version (pv): 1.0
State Number (s#): 1
Status Flags (sf): 0
Category Identifier (ci): Video Door Bell (Id: 18)
```

**Comment by jlusiardi** [comment]
I guess this device may have cause your issue: 
```
Name:` ðŸ’¦ Sprinkler-C551._hap._tcp.local.
Url: http://192.168.1.91:52833
Configuration number (c#): 2
Feature Flags (ff): Paired (Flag: 0)
Device ID (id): A3:AB:3D:4D:2E:A3
Model Name (md): ðŸ’¦ Sprinkler
Protocol Version (pv): 1.0
State Number (s#): 1
Status Flags (sf): 0
Category Identifier (ci): Other (Id: 1)
```
Since it is a sprinkler, using the emoticon 💦 (https://emojidictionary.emojifoundation.com/sweat_droplets#hl=n_1bfb4) in the name is kind of interesting...

**Comment by jlusiardi** [comment]
i guess i fixed it. can you confirm the branch is working? 

This should now print a **_?_** instead of a potential non printable character:
```
LANG=c  python3 homekit/discover.py
```
