### ISSUE TITLE
Not possible to remove pairing with a BLE accessory

### ISSUE THREAD

**Issue by jlusiardi** [jlusiardi/homekit_python#77]
Currently it is not possible to remove a BLE pairing:
`PYTHONPATH=. python3 homekit/unpair.py --log DEBUG  -f ble.json -a DW1`

This fails:
```
2019-01-11 06:40:16,366 ble_implementation.py:0292 DEBUG body: bytearray(b'\x06\x01\x01\x00\x01\x04\x01$066c8ca0-72ff-4e79-a2fd-be6ec86c77c6')
2019-01-11 06:40:16,371 ble_implementation.py:0299 DEBUG cipher and mac ade106a4434ab390d675d9033c18a0bd4f56a0a4a1e03d1f720e837fe83cd4ef9fe587c7c3c91aadfc91b31bd8f7de28db3a2bf4f32df84f91f12a6a16717dbd75
2019-01-11 06:40:16,371 ble_implementation.py:0302 DEBUG write resulted in: None
2019-01-11 06:40:17,373 ble_implementation.py:0309 DEBUG reading characteristic
Traceback (most recent call last):
  File "homekit/unpair.py", line 44, in <module>
    controller.remove_pairing(args.alias)
  File "/home/jlusiardi/Dokumente/src/homekit_python/homekit/controller/controller.py", line 315, in remove_pairing
    response = session.request(pair_remove_char, pair_remove_char_id, HapBleOpCodes.CHAR_WRITE, request_tlv)
  File "/home/jlusiardi/Dokumente/src/homekit_python/homekit/controller/ble_implementation.py", line 312, in request
    raise RuntimeError('Read failed')
RuntimeError: Read failed
``` 

The code starts roughly at https://github.com/jlusiardi/homekit_python/blob/add_bluetooth/homekit/controller/controller.py#L286

**Comment by Jc2k** [comment]
It's just an invalid value that you are passing into BleSession.request:

```
diff --git a/homekit/controller/controller.py b/homekit/controller/controller.py
index f53f5a0..be7584a 100644
--- a/homekit/controller/controller.py
+++ b/homekit/controller/controller.py
@@ -290,6 +290,8 @@ class Controller(object):
                 (TLV.kTLVType_Identifier, pairing_data['iOSPairingId'].encode())
             ])
 
+            body = len(request_tlv).to_bytes(length=2, byteorder='little') + request_tlv
+
             class AnyDevice(staging.gatt.gatt_linux.Device):
                 def services_resolved(self):
                     super().services_resolved()
@@ -309,7 +311,8 @@ class Controller(object):
             session = BleSession(pairing_data)
             from homekit.protocol.opcodes import HapBleOpCodes
 
-            response = session.request(pair_remove_char, pair_remove_char_id, HapBleOpCodes.CHAR_WRITE, request_tlv)
+            response = session.request(pair_remove_char, pair_remove_char_id, HapBleOpCodes.CHAR_WRITE, body)
             logging.debug('response: %s', response)
+
         else:
             raise Exception('not implemented')
```

With that I get a validresponse with a status code of 0, however it doesnt decode into what i'd expect from reading the spec. And my pairing still works after. So while this is "more right" we are still missing something.

**Comment by Jc2k** [comment]
Ok, got it:

```
diff --git a/homekit/controller/controller.py b/homekit/controller/controller.py
index f53f5a0..fa5663b 100644
--- a/homekit/controller/controller.py
+++ b/homekit/controller/controller.py
@@ -290,6 +290,13 @@ class Controller(object):
                 (TLV.kTLVType_Identifier, pairing_data['iOSPairingId'].encode())
             ])
 
+            inner = TLV.encode_list([
+                (TLV.kTLVHAPParamParamReturnResponse, bytearray(b'\x01')),
+                (TLV.kTLVHAPParamValue, request_tlv)
+            ])
+
+            body = len(inner).to_bytes(length=2, byteorder='little') + inner
+
             class AnyDevice(staging.gatt.gatt_linux.Device):
                 def services_resolved(self):
                     super().services_resolved()
@@ -309,7 +316,14 @@ class Controller(object):
             session = BleSession(pairing_data)
             from homekit.protocol.opcodes import HapBleOpCodes
 
-            response = session.request(pair_remove_char, pair_remove_char_id, HapBleOpCodes.CHAR_WRITE, request_tlv)
+            response = session.request(pair_remove_char, pair_remove_char_id, HapBleOpCodes.CHAR_WRITE, body)
             logging.debug('response: %s', response)
+
+            inner = TLV.decode_bytes(response[1])
+            logging.debug('inner: %s', inner)
+
+            # FIXME: Need to make sure there isnt a kTLVType_Error in inner here
+            # assert TLV.kTLVType_Error not in inner
```

I have too many PR's / branches in flight to add another, but hopefully this is enough for you to close off this issue.

**Comment by jlusiardi** [comment]
Ok I guess I will integrate this tonight ;) thanks.

**Comment by Jc2k** [comment]
Cool - hoping to get a BLE pairing test written tonight / tomorrow am

**Comment by jlusiardi** [comment]
ok, i guess this works right now, but testing is not possible without some accessory and adapter. :-1: 

I'll tune some aspects and then commit

**Comment by jlusiardi** [comment]
checked the pair & unpair cycle for BLE and IP. Both work.
